app: TiddlyDesktop

ingredients:
  script:
    - DLD=$(wget -q "https://api.github.com/repos/Jermolene/TiddlyDesktop/releases/latest" -O - | grep -E "https.*tiddlydesktop-linux64" | cut -d'"' -f4)
    - wget -c $DLD
    - unzip tiddlydesktop-linux64-*.zip

  script:
    - VER=$(wget -q "https://api.github.com/repos/Jermolene/TiddlyDesktop/releases/latest" -O - | grep tag_name | cut -d'"' -f4)
    - echo $VER > VERSION

script:
  - cp TiddlyDesktop-linux64-*/images/app-icon.png TiddlyDesktop.png
  - mv TiddlyDesktop.png TiddlyDesktop-linux64-*/
  - cat > ./TiddlyDesktop.desktop <<\EOF
  - [Desktop Entry]
  - Type=Application
  - Name=TiddlyDesktop
  - Icon=TiddlyDesktop
  - Exec=nw %u
  - Categories=Editor;
  - MimeType=text/html;text/xml;application/xhtml+xml;
  - StartupNotify=true
  - EOF
